services:
  server:
    build: .
    environment:
      - DATABASE=postgres://mainuser:12345678@db:5432/main
      - RUST_LOG=debug
    ports:
      - "35124:80"

  db:
    build: ./postgresdb
    environment:
      POSTGRES_USER: mainuser
      POSTGRES_PASSWORD: '12345678'
      POSTGRES_DB: main
    ports:
      - "5432:5432"
    volumes:
      - backend_data:/var/lib/postgresql/data

volumes:
  backend_data: